Sender: LSF System <lsfadmin@eu-g3-061>
Subject: Job 212070730: <python logicclimate.py -t /cluster/project/sachan/abhinav/saved_models/electra-mnli -m /cluster/project/sachan/abhinav/saved_models/electra-mnli -w 12 -ts 1 -ds 1 -f T -s /cluster/project/sachan/abhinav/saved_models/electra-lc-ft -mp base> in cluster <euler> Exited

Job <python logicclimate.py -t /cluster/project/sachan/abhinav/saved_models/electra-mnli -m /cluster/project/sachan/abhinav/saved_models/electra-mnli -w 12 -ts 1 -ds 1 -f T -s /cluster/project/sachan/abhinav/saved_models/electra-lc-ft -mp base> was submitted from host <eu-login-06> by user <alalwani> in cluster <euler> at Fri Apr  1 14:01:31 2022
Job was executed on host(s) <eu-g3-061>, in queue <gpuhe.4h>, as user <alalwani> in cluster <euler> at Fri Apr  1 14:02:00 2022
</cluster/home/alalwani> was used as the home directory.
</cluster/home/alalwani/logical-fallacy/data> was used as the working directory.
Started at Fri Apr  1 14:02:00 2022
Terminated at Fri Apr  1 14:02:01 2022
Results reported at Fri Apr  1 14:02:01 2022

Your job looked like:

------------------------------------------------------------
# LSBATCH: User input
python logicclimate.py -t /cluster/project/sachan/abhinav/saved_models/electra-mnli -m /cluster/project/sachan/abhinav/saved_models/electra-mnli -w 12 -ts 1 -ds 1 -f T -s /cluster/project/sachan/abhinav/saved_models/electra-lc-ft -mp base
------------------------------------------------------------

Exited with exit code 2.

Resource usage summary:

    CPU time :                                   0.20 sec.
    Max Memory :                                 6 MB
    Average Memory :                             -
    Total Requested Memory :                     30000.00 MB
    Delta Memory :                               29994.00 MB
    Max Swap :                                   -
    Max Processes :                              -
    Max Threads :                                -
    Run time :                                   1 sec.
    Turnaround time :                            30 sec.

The output (if any) follows:

python: can't open file '/cluster/home/alalwani/logical-fallacy/data/logicclimate.py': [Errno 2] No such file or directory
